#!/usr/bin/env bash

which bork || curl https://raw.githubusercontent.com/josh-lauer/bork/master/install?`uuidgen` | bash -s

BORK_PWD=`pwd`
cd ~/.bork/bork
rvm use ruby-2.4.1@bork
~/.bork/bork/bin/bork -c $BORK_PWD
