#!/usr/bin/env bash

# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
  exit 1
fi

echo "Installing ruby-2.4.1 with rvm"
rvm install "ruby-2.4.1"

echo "Creating bork dir"
mkdir ~/.bork && cd ~/.bork
rm -rf ~/.bork/bork && git clone https://github.com/josh-lauer/bork.git ~/.bork/bork
cd ~/.bork/bork

echo "INSTALLING BUNDLER"
gem install bundler
bundle install

echo "Installing binstub."
curl https://raw.githubusercontent.com/josh-lauer/bork/master/binstub?`uuidgen` > /usr/local/bin/bork
chmod +x /usr/local/bin/bork
echo "Bork Installed."
