#!/usr/bin/env bash

# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
  exit 1
fi

cd && mkdir .bork && cd .bork
ls -la ~/.bork
echo "ABOUT TO CLONE"
rm -rf ~/.bork/bork && git clone https://github.com/josh-lauer/bork.git ~/.bork/bork
echo "JUST CLONED"
cd bork
rvm use ruby-2.4.1@bork
gem install bundler
bundle install

curl https://raw.githubusercontent.com/josh-lauer/bork/master/binstub?foo=`uuidgen` > /usr/local/bin/bork
chmod +x /usr/local/bin/bork
echo "Bork Installed."
